name: Update Icons Array

on:
  push:
    branches:
      - main

jobs:
  update-icons:
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'Pushing latest icon updates from local changes')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run icon updater
        run: |
          echo "Running because commit message contains 'Pushing latest icon updates from local changes'"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run conversion script
        run: node scripts/build.js

      - name: Debug token identity
        env:
          TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://api.github.com/user

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "you@example.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Zohocorp-Pvt-Ltd/Bigin-UI-Team.git
          git add dist/ux-icons-holder.js
          git diff --cached --quiet || git commit -m "🚀 Auto-generated ux-icons-holder.js from HTML"
          git push origin HEAD:main

